apiVersion: keycloak.k8s.reddec.net/v1alpha1
kind: KeycloakClient
metadata:
  name: keycloakclient-sample
spec:
  secretName: "oauth" # optional, if not set the CRD name will be used
  domain: "example.com"
  realm: reddec
